--!strict

local Controllers = script.Parent.Controllers

require(Controllers.HUDController).start()
require(Controllers.RankUpController).start()
require(Controllers.DonationController).start()
require(Controllers.StandManagerController).start()
require(Controllers.XPShopController).start()
require(Controllers.WorldSelectController).start()
require(Controllers.QuestController).start()
require(Controllers.LeaderboardController).start()
require(Controllers.TitlesController).start()
require(Controllers.ChatTagController).start()
require(Controllers.JoinAnnouncementController).start()
